In [ ]:
import pandas as pd

In [ ]:
output = pd.read_csv('/content/output.csv')
output

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,Log into your Facebook account to share.Phone ...,English (US),+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# nan 행 제거
output = output.drop(labels=range(0,6))
output

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
6,1,일반버스,천안시청,백석농공단지,06시 00분,22시 45분,\n,1.0,천안시청,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,일반버스,백석농공단지,천안시청,06시 00분,22시 45분,\n,1.0,백석농공단지,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10,일반버스,천안시청,천안시청,22시 00분,03시 00분,\n,1.0,천안시청,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,일반버스,천안시청,천안시청,22시 00분,03시 00분,\n,1.0,천안시청,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,100,일반버스,신부경남아파트,남서울대학교 주차장,06시 00분,22시 05분,\n,1.0,신부경남아파트,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,Log into your Facebook account to share.Phone ...,English (US),+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output = output.drop(output.columns[[1,2,3,4,5,6]],axis=1)
output

,Unnamed: 0,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
6,1,1.0,천안시청,2.0,천안시청 서북구보건소,3.0,불당동일하이빌,4.0,불당대동다숲,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,1.0,백석농공단지,2.0,화성조명,3.0,한들문화센터입구,4.0,STS,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10,1.0,천안시청,2.0,천안시청시의회,3.0,불당상업지구입구,4.0,서울대정병원,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,1.0,천안시청,2.0,백석11단지,3.0,백석그린빌아파트,4.0,두정부경아파트,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,100,1.0,신부경남아파트,2.0,천안중학교,3.0,교보생명,4.0,교보사거리,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,Log into your Facebook account to share.Phone ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output = output[:280]  # 0번째부터 285번째 항목까지 유지됩니다
output

,Unnamed: 0,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
6,1,1.0,천안시청,2.0,천안시청 서북구보건소,3.0,불당동일하이빌,4.0,불당대동다숲,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,1.0,백석농공단지,2.0,화성조명,3.0,한들문화센터입구,4.0,STS,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10,1.0,천안시청,2.0,천안시청시의회,3.0,불당상업지구입구,4.0,서울대정병원,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,1.0,천안시청,2.0,백석11단지,3.0,백석그린빌아파트,4.0,두정부경아파트,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,100,1.0,신부경남아파트,2.0,천안중학교,3.0,교보생명,4.0,교보사거리,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,95,1.0,월봉청솔아파트,2.0,용암마을,3.0,쌍용한라동백아파트,4.0,삼일육아원,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,97,1.0,"신방도서관, 푸르지오아파트",2.0,새마을금고,3.0,한성필하우스,4.0,하나리움,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,97,1.0,업성고교,2.0,서북경찰서,3.0,번영로공구상가,4.0,2공단입구,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,98,1.0,청당벽산아파트,2.0,청삼교차로,3.0,우미린아파트,4.0,"우미린,한양수자인아파트",5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,99,1.0,직산대림아파트,2.0,천안산업단지관리공단,3.0,롯데푸드,4.0,차암공단입구,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output.reset_index(inplace=True)
output

,index,Unnamed: 0,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,6,1,1.0,천안시청,2.0,천안시청 서북구보건소,3.0,불당동일하이빌,4.0,불당대동다숲,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,1,1.0,백석농공단지,2.0,화성조명,3.0,한들문화센터입구,4.0,STS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,10,1.0,천안시청,2.0,천안시청시의회,3.0,불당상업지구입구,4.0,서울대정병원,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,10,1.0,천안시청,2.0,백석11단지,3.0,백석그린빌아파트,4.0,두정부경아파트,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10,100,1.0,신부경남아파트,2.0,천안중학교,3.0,교보생명,4.0,교보사거리,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,281,95,1.0,월봉청솔아파트,2.0,용암마을,3.0,쌍용한라동백아파트,4.0,삼일육아원,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,282,97,1.0,"신방도서관, 푸르지오아파트",2.0,새마을금고,3.0,한성필하우스,4.0,하나리움,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,283,97,1.0,업성고교,2.0,서북경찰서,3.0,번영로공구상가,4.0,2공단입구,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,284,98,1.0,청당벽산아파트,2.0,청삼교차로,3.0,우미린아파트,4.0,"우미린,한양수자인아파트",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,285,99,1.0,직산대림아파트,2.0,천안산업단지관리공단,3.0,롯데푸드,4.0,차암공단입구,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output_2 = output.drop(['index'],axis=1)
output_2

,Unnamed: 0,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,1,1.0,천안시청,2.0,천안시청 서북구보건소,3.0,불당동일하이빌,4.0,불당대동다숲,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1.0,백석농공단지,2.0,화성조명,3.0,한들문화센터입구,4.0,STS,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,1.0,천안시청,2.0,천안시청시의회,3.0,불당상업지구입구,4.0,서울대정병원,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,1.0,천안시청,2.0,백석11단지,3.0,백석그린빌아파트,4.0,두정부경아파트,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100,1.0,신부경남아파트,2.0,천안중학교,3.0,교보생명,4.0,교보사거리,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,95,1.0,월봉청솔아파트,2.0,용암마을,3.0,쌍용한라동백아파트,4.0,삼일육아원,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,97,1.0,"신방도서관, 푸르지오아파트",2.0,새마을금고,3.0,한성필하우스,4.0,하나리움,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,97,1.0,업성고교,2.0,서북경찰서,3.0,번영로공구상가,4.0,2공단입구,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,98,1.0,청당벽산아파트,2.0,청삼교차로,3.0,우미린아파트,4.0,"우미린,한양수자인아파트",5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,99,1.0,직산대림아파트,2.0,천안산업단지관리공단,3.0,롯데푸드,4.0,차암공단입구,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
output_2.to_csv('output_2.csv')

NameError: ignored

In [ ]:
bus_stop = pd.read_csv('/content/output_2.csv')
bus_stop.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,0,1,1.0,천안시청,2.0,천안시청 서북구보건소,3.0,불당동일하이빌,4.0,불당대동다숲,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1.0,백석농공단지,2.0,화성조명,3.0,한들문화센터입구,4.0,STS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10,1.0,천안시청,2.0,천안시청시의회,3.0,불당상업지구입구,4.0,서울대정병원,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10,1.0,천안시청,2.0,백석11단지,3.0,백석그린빌아파트,4.0,두정부경아파트,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,100,1.0,신부경남아파트,2.0,천안중학교,3.0,교보생명,4.0,교보사거리,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(bus_stop)

280

In [ ]:
bus_1 = bus_stop.loc[[0]]
bus_1['Unnamed: 0']

0    1
Name: Unnamed: 0, dtype: int64

In [ ]:
bus_1 = bus_stop.loc[[0]]
bus_1 = bus_1.melt()
new_data = []

for i, row in enumerate(bus_1.iloc[1::2].iterrows(), start=1):
    _, data = row
    route_name = data[0]
    direction = data[1]
    if pd.notna(direction):  # NaN 값이 아닌 경우에만 추가
        new_data.append([1, i-1, direction])

# 추출한 데이터로 새로운 데이터프레임 생성
df_new = pd.DataFrame(new_data, columns=['버스노선번호', '몇번째 정류장', '노선이름'])

# 0번째 행을 지우고 결과 출력
df_new = df_new.drop(0)

In [ ]:
df_new

    버스노선번호  몇번째 정류장          노선이름
1        1        1          천안시청
2        1        2   천안시청 서북구보건소
3        1        3       불당동일하이빌
4        1        4        불당대동다숲
5        1        5       불당한성아파트
6        1        6       천안교육지원청
7        1        7     충남북부상공회의소
8        1        8         패션1광장
9        1        9          펜타포트
10       1       10           서당골
11       1       11       갤러리아백화점
12       1       12     불당동문화카페거리
13       1       13         월봉중학교
14       1       14     한화꿈에그린아파트
15       1       15         쌍용도서관
16       1       16       월봉벽산아파트
17       1       17     월봉5차현대아파트
18       1       18         쌍용고입구
19       1       19       삼일원앙아파트
20       1       20    쌍용역해누리아이파크
21       1       21         쌍용고가교
22       1       22       쌍용동 이마트
23       1       23          충무병원
24       1       24  다가동신성아파트YWCA
25       1       25        일봉초등학교
26       1       26         남부오거리
27       1       27     우성VIP 아파트
28       1       28        천안여중입구
29       1       29       원성극동아파트
30       1       30         교보사거리
31       1       31          교보생명
32       1       32        중앙고등학교
33       1       33       신부경남아파트
34       1       34         고속터미널
35       1       35      가구웨딩특화거리
36       1       36         백석사거리
37       1       37        백석종합상가
38       1       38        백석초등학교
39       1       39    주공그린빌3차아파트
40       1       40        백석11단지
41       1       41          천안시청
42       1       42       천안시청시의회
43       1       43         종합운동장
44       1       44      벽산블루밍아파트
45       1       45          한국더첼
46       1       46         화이트스톤
47       1       47      한들문화센터입구
48       1       48          영진기계
49       1       49        백석농공단지

In [ ]:
new_data = []

for j in range(len(bus_stop)):
    bus_j = bus_stop.loc[[j]]
    bus_j = bus_j.melt()

    for i, row in enumerate(bus_j.iloc[1::2].iterrows(), start=1):
        _, data = row
        route_name = data[0]
        direction = data[1]
        bus_num = bus_j['Unnamed: 0'] # bus_num을 j번째 값으로 추출

        if pd.notna(direction):
            new_data.append([bus_num, i - 1, direction])

# 추출한 데이터로 새로운 데이터프레임 생성
df_new_bus = pd.DataFrame(new_data, columns=['버스노선번호', '몇번째 정류장', '노선이름'])

KeyError: ignored

In [ ]:
df_new_bus

                                                 버스노선번호  몇번째 정류장         노선이름
0     variable    Unnamed: 0
value                1
...        0            1
1     variable    Unnamed: 0
value                1
...        1         천안시청
2     variable    Unnamed: 0
value                1
...        2  천안시청 서북구보건소
3     variable    Unnamed: 0
value                1
...        3      불당동일하이빌
4     variable    Unnamed: 0
value                1
...        4       불당대동다숲
...                                                 ...      ...          ...
9243  variable    Unnamed: 0
value               99
...        6      이마트 서북점
9244  variable    Unnamed: 0
value               99
...        7      이마트 서북점
9245  variable    Unnamed: 0
value               99
...        8    두정대림2차아파트
9246  variable    Unnamed: 0
value               99
...        9  천안시장애인종합복지관
9247  variable    Unnamed: 0
value               99
...       10      두정우성아파트

[9248 rows x 3 columns]

In [ ]:
# bus_stop 데이터프레임 읽기
bus_stop = pd.read_csv('./output_2.csv')

# 새로운 데이터프레임을 담을 딕셔너리 생성
bus_dataframes = {}

# for 루프를 사용하여 데이터프레임 생성 및 처리
for i in range(len(bus_stop)):
    # 각 행을 데이터프레임으로 생성
    bus_dataframes[i] = bus_stop.loc[[i]].melt()

# 새로운 데이터프레임을 만들기 위한 빈 리스트 생성
new_data = []

# 각 데이터프레임을 for 루프로 순회하며 데이터 처리
for i in range(len(bus_stop)):
    for j, row in enumerate(bus_dataframes[i].iloc[1::2].iterrows(), start=1):
        _, data = row
        route_name = data[0]
        direction = data[1]
        if pd.notna(direction):  # NaN 값이 아닌 경우에만 추가
            new_data.append([i + 1, j, direction])

# 추출한 데이터로 새로운 데이터프레임 생성
df_new = pd.DataFrame(new_data, columns=['버스노선번호', '몇번째 정류장', '노선이름'])

df_new.to_csv('output_busstop.csv',encoding='utf-8')